<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 20px; margin: 0; }
        .header p { font-size: 12px; color: #666; margin: 5px 0; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        th { background-color: #f2f2f2; font-weight: bold; padding: 8px; text-align: left; border: 1px solid #ddd; }
        td { padding: 6px 8px; border: 1px solid #ddd; }
        .status-active { color: green; }
        .status-expired { color: red; }
        .status-depleted { color: orange; }
        .status-quarantined { color: purple; }
        .footer { text-align: center; font-size: 10px; color: #666; margin-top: 20px; }
        .badge { 
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-active { background-color: #d4edda; color: #155724; }
        .badge-expired { background-color: #f8d7da; color: #721c24; }
        .badge-depleted { background-color: #fff3cd; color: #856404; }
        .badge-quarantined { background-color: #d1ecf1; color: #0c5460; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated: {{ $date }}</p>
        <p>Total Batches: {{ $batches->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Batch Number</th>
                <th>Drug</th>
                <th>Supplier</th>
                <th>Quantity</th>
                <th>Unit Cost</th>
                <th>Expiry Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($batches as $batch)
            <tr>
                <td>{{ $batch->id }}</td>
                <td>{{ $batch->batch_number }}</td>
                <td>{{ $batch->drug->name ?? 'N/A' }}</td>
                <td>{{ $batch->supplier->name ?? 'N/A' }}</td>
                <td>{{ $batch->quantity }}</td>
                <td>{{ $batch->unit_cost ? 'UGX '.number_format($batch->unit_cost, 2) : 'N/A' }}</td>
                <td>{{ $batch->expiry_date->format('Y-m-d') }}</td>
                <td>
                    <span class="badge badge-{{ $batch->status }}">
                        {{ ucfirst($batch->status) }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Mpigi Pharmacy Management System</p>
    </div>
</body>
</html>