<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 20px; margin: 0; }
        .header p { font-size: 12px; color: #666; margin: 5px 0; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        th { background-color: #f2f2f2; font-weight: bold; padding: 8px; text-align: left; border: 1px solid #ddd; }
        td { padding: 6px 8px; border: 1px solid #ddd; }
        .status-active { color: green; font-weight: bold; }
        .status-inactive { color: red; font-weight: bold; }
        .footer { text-align: center; font-size: 10px; color: #666; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated: {{ $date }}</p>
        <p>Total Drugs: {{ $drugs->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Generic Name</th>
                <th>Category</th>
                <th>Manufacturer</th>
                <th>Unit</th>
                <th>Total Stock</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($drugs as $drug)
            <tr>
                <td>{{ $drug->id }}</td>
                <td>{{ $drug->name }}</td>
                <td>{{ $drug->generic_name ?? 'N/A' }}</td>
                <td>{{ $drug->category ?? 'N/A' }}</td>
                <td>{{ $drug->manufacturer ?? 'N/A' }}</td>
                <td>{{ $drug->unit }}</td>
                <td>{{ $drug->total_stock }}</td>
                <td class="{{ $drug->is_active ? 'status-active' : 'status-inactive' }}">
                    {{ $drug->is_active ? 'Active' : 'Inactive' }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Mpigi Pharmacy Management System</p>
    </div>
</body>
</html>