{{-- resources/views/reports/suppliers.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { 
            font-family: DejaVu Sans, sans-serif; 
            margin: 20px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 { 
            font-size: 24px; 
            margin: 0; 
            color: #1a56db;
        }
        .header p { 
            font-size: 12px; 
            color: #666; 
            margin: 5px 0; 
        }
        .header .count {
            font-size: 14px;
            color: #333;
            font-weight: bold;
            margin-top: 10px;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            font-size: 11px; 
            margin-top: 15px;
        }
        th { 
            background-color: #f2f2f2; 
            font-weight: bold; 
            padding: 10px 8px; 
            text-align: left; 
            border: 1px solid #ddd; 
            color: #333;
        }
        td { 
            padding: 8px; 
            border: 1px solid #ddd; 
        }
        .status-active { 
            color: #155724; 
            font-weight: bold;
            background-color: #d4edda;
            padding: 2px 10px;
            border-radius: 4px;
            display: inline-block;
        }
        .status-inactive { 
            color: #721c24; 
            font-weight: bold;
            background-color: #f8d7da;
            padding: 2px 10px;
            border-radius: 4px;
            display: inline-block;
        }
        .footer { 
            text-align: center; 
            font-size: 10px; 
            color: #666; 
            margin-top: 30px;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
        .badge {
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-active { background-color: #d4edda; color: #155724; }
        .badge-inactive { background-color: #f8d7da; color: #721c24; }
        .text-muted { color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated: {{ $date }}</p>
        <p class="count">Total Suppliers: {{ $suppliers->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Contact Person</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Address</th>
                <th>Tax ID</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($suppliers as $supplier)
            <tr>
                <td>{{ $supplier->id }}</td>
                <td><strong>{{ $supplier->name }}</strong></td>
                <td>{{ $supplier->contact_person ?? 'N/A' }}</td>
                <td>{{ $supplier->phone ?? 'N/A' }}</td>
                <td>{{ $supplier->email ?? 'N/A' }}</td>
                <td>{{ $supplier->address ?? 'N/A' }}</td>
                <td>{{ $supplier->tax_id ?? 'N/A' }}</td>
                <td>
                    <span class="badge badge-{{ $supplier->is_active ? 'active' : 'inactive' }}">
                        {{ $supplier->is_active ? 'Active' : 'Inactive' }}
                    </span>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="8" style="text-align: center; color: #999; padding: 20px;">
                    No suppliers found.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Mpigi Pharmacy Management System</p>
        <p>{{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>